const ADD_ITEM = 'ADD_ITEM'
const EDIT_ITEM = 'EDIT_ITEM'
const DELETE_ITEM = 'DELETE_ITEM'
const FETCH_ITEMS = 'FETCH_ITEMS'
const FETCH_ITEMS_SUCCESS = 'FETCH_ITEMS_SUCCESS'
const FETCH_ITEMS_ERROR = 'FETCH_ITEMS_ERROR'

export default {
  ADD_ITEM,
  EDIT_ITEM,
  DELETE_ITEM,
  FETCH_ITEMS,
  FETCH_ITEMS_SUCCESS,
  FETCH_ITEMS_ERROR
}
